version: '3'

services:
  liststd:
    build: ./liststd
    volumes:
      - ./liststd:/usr/src/app
    ports:
      - 5000:80

  website:
    image: centos:7 
    volumes:
      - ./website:/var/www/html
    ports:
      - 3000:80
    depends_on:
      - liststd
